### ISSUE TITLE
selinux-enforcing fingerprint fix

### ISSUE THREAD

**Issue by alex9yust** [YuKongA/device_xiaomi_marble#2]
fingerprint works in enforcing . maybe something extra.
[fingerprint1.zip](https://github.com/marble-development/android_device_xiaomi_marble/files/12445291/fingerprint1.zip)

**Comment by YuKongA** [comment]
thx for your work!

**Comment by YuKongA** [comment]
There still seems to be a problem with fpc fingerprint, but mine is goodix

**Comment by alex9yust** [comment]
mine is goodix too. sorry.
by the way, why is it not visible in the logs of messages from selinux ?

**Comment by YuKongA** [comment]
milt kernel disable avc logs, just switch to normal kernel
